# Generated by Django 5.2.8 on 2026-02-26 05:35

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhouseManager',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('whouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhouseManagerResetPasswordSession',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('otp', models.IntegerField(default=123456)),
                ('last_sms_time', models.DateTimeField(auto_now_add=True)),
                ('uses', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('whouse_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_whouse_manager.whousemanager')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
