# Generated by Django 5.2.8 on 2026-02-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
        ('factory_whouse_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whousemanager',
            name='whouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whouse_managers', to='factory_whouse.whouse'),
        ),
    ]
