# Generated by Django 5.2.8 on 2026-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
        ('factory_whouse_manager', '0002_alter_whousemanager_whouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whousemanager',
            name='whouse',
        ),
        migrations.AddField(
            model_name='whousemanager',
            name='whouses',
            field=models.ManyToManyField(related_name='managers', to='factory_whouse.whouse'),
        ),
    ]
