# Generated by Django 5.2.8 on 2026-03-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0021_alter_excavatororder_rejector_id'),
        ('notifications', '0002_notification_to_user_id'),
        ('orders', '0021_alter_suborder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='excavator_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='excavator.excavatorsuborder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.suborder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('EXCAVATOR_SUB_ORDER', 'Excavator Sub Order'), ('SUB_ORDER', 'Sub Order')], max_length=255, null=True),
        ),
    ]
