# Generated by Django 5.2.8 on 2026-03-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatas', '0001_initial'),
        ('users', '0002_factoryuser_wherehouses_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.factoryuser'),
        ),
    ]
