# Generated by Django 5.2.8 on 2026-03-06 11:40

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_client_photo'),
        ('factory_drivers', '0003_driver_photo'),
        ('factory_whouse', '0001_initial'),
        ('filedatas', '0002_alter_file_user'),
        ('products', '0002_remove_whouseproductshistory_files_and_more'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_id', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('external_drivers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.clientbranches')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.producttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.productunit')),
                ('whouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='factory_whouse.whouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='factory_drivers.driver')),
                ('files', models.ManyToManyField(related_name='sub_orders', to='filedatas.file')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='transports.transport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
