# Generated by Django 5.2.8 on 2026-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed')], default='NEW', max_length=20),
        ),
    ]
