# Generated by Django 5.2.8 on 2026-03-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_photo'),
        ('orders', '0002_alter_order_status_alter_suborder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.clientbranches'),
        ),
    ]
