# Generated by Django 5.2.8 on 2026-03-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_photo'),
        ('factory_drivers', '0003_driver_photo'),
        ('factory_whouse', '0001_initial'),
        ('orders', '0003_alter_order_branch'),
        ('products', '0002_remove_whouseproductshistory_files_and_more'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.producttype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.productunit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='whouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='factory_whouse.whouse'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='factory_drivers.driver'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='transports.transport'),
        ),
    ]
