# Generated by Django 5.2.8 on 2026-03-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_user'),
        ('orders', '0004_alter_order_client_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders_sign', to='files.file'),
        ),
    ]
