# Generated by Django 5.2.8 on 2026-03-10 10:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_suborder_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='status_history',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
