# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_suborder_status_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='files',
        ),
    ]
