# Generated by Django 5.2.8 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatas', '0006_alter_documents_type'),
        ('orders', '0007_remove_suborder_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='sub_orders_files', to='filedatas.file'),
        ),
    ]
