# Generated by Django 5.2.8 on 2026-03-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_suborder_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
