# Generated by Django 5.2.8 on 2026-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejector',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('FACTORY', 'Factory')], default='CLIENT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
