# Generated by Django 5.2.8 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_rejector_alter_suborder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
