# Generated by Django 5.2.8 on 2026-03-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_drivers',
        ),
    ]
