# Generated by Django 5.2.8 on 2026-03-23 17:02

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_external_drivers'),
        ('products', '0010_alter_productitem_raw_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejector',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
        migrations.AddField(
            model_name='order',
            name='rejector_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejector_role',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('FACTORY', 'Factory')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.producttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrderItem',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_order_items', to='products.product')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_order_items', to='orders.suborder')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_order_items', to='products.producttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_order_items', to='products.productunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
