# Generated by Django 5.2.8 on 2026-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rejector_role',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('OPERATOR', 'Operator'), ('MANAGER', 'Manager')], max_length=20, null=True),
        ),
    ]
