# Generated by Django 5.2.8 on 2026-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_documents_type'),
        ('orders', '0015_alter_order_rejector_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_orders_files', to='files.file'),
        ),
    ]
