# Generated by Django 5.2.8 on 2026-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_suborder_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='quantity',
        ),
    ]
