# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0013_alter_driver_options_alter_driver_unique_together'),
        ('orders', '0018_remove_duplicate_suborders'),
        ('products', '0010_alter_productitem_raw_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suborder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suborderitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product', 'type', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='suborder',
            unique_together={('order', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='suborderitem',
            unique_together={('sub_order', 'product', 'type', 'unit')},
        ),
    ]
