# Generated by Django 5.2.8 on 2026-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_options_alter_suborder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ON_WAY', 'On Way'), ('ARRIVED', 'Arrived'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
