# Generated by Django 5.2.8 on 2026-03-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status_alter_suborder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborder',
            options={'ordering': ['-created_at']},
        ),
    ]
