# Generated by Django 5.2.8 on 2026-02-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_session', '0001_initial'),
        ('factory_whouse_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhouseManagerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whouse_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='factory_whouse_manager.whousemanager')),
            ],
        ),
    ]
