# Generated by Django 5.2.8 on 2026-02-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_operator', '0001_initial'),
        ('factory_session', '0002_whousemanagersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOperatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='factory_operator.factoryoperator')),
            ],
        ),
    ]
