# Generated by Django 5.2.8 on 2026-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_session', '0003_factoryoperatorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
