# Generated by Django 5.2.8 on 2026-02-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_session', '0004_guardsession'),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardsession',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='guard.guard'),
        ),
    ]
