# Generated by Django 5.2.8 on 2026-03-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_session', '0005_guardsession_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='factoryoperatorsession',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='guardsession',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='whousemanagersession',
            name='whouse_manager',
        ),
    ]
