# Generated by Django 5.2.8 on 2026-03-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('crud_whouse_manager', models.BooleanField(default=False)),
                ('crud_factory_operator', models.BooleanField(default=False)),
                ('crud_driver', models.BooleanField(default=False)),
                ('crud_guard', models.BooleanField(default=False)),
                ('crud_product', models.BooleanField(default=False)),
                ('crud_transport', models.BooleanField(default=False)),
                ('crud_client', models.BooleanField(default=False)),
                ('read_whouse', models.BooleanField(default=False)),
                ('read_whouse_manager', models.BooleanField(default=False)),
                ('read_factory_operator', models.BooleanField(default=False)),
                ('read_driver', models.BooleanField(default=False)),
                ('read_guard', models.BooleanField(default=False)),
                ('read_product', models.BooleanField(default=False)),
                ('read_transport', models.BooleanField(default=False)),
                ('read_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('whouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
