# Generated by Django 5.2.8 on 2026-03-04 05:13

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('MAIN_PAGE', models.BooleanField(default=False)),
                ('PRODUCTS_PAGE', models.BooleanField(default=False)),
                ('ORDERS_PAGE', models.BooleanField(default=False)),
                ('TRANSPORTS_PAGE', models.BooleanField(default=False)),
                ('CLIENTS_PAGE', models.BooleanField(default=False)),
                ('USERS_PAGE', models.BooleanField(default=False)),
                ('READY_PRODUCTS_PAGE', models.BooleanField(default=False)),
                ('DRIVERS_PAGE', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('whouses', models.ManyToManyField(blank=True, related_name='users', to='factory_whouse.whouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
