# Generated by Django 5.2.8 on 2026-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryuser',
            name='whouse',
        ),
        migrations.AddField(
            model_name='factoryuser',
            name='whouses',
            field=models.ManyToManyField(blank=True, related_name='users', to='factory_whouse.whouse'),
        ),
    ]
