# Generated by Django 5.2.8 on 2026-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoryuser',
            old_name='clients_page',
            new_name='CLIENTS_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='main_page',
            new_name='MAIN_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='orders_page',
            new_name='ORDERS_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='products_page',
            new_name='PRODUCTS_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='settings_page',
            new_name='SETTINGS_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='transports_page',
            new_name='TRANSPORTS_PAGE',
        ),
        migrations.RenameField(
            model_name='factoryuser',
            old_name='users_page',
            new_name='USERS_PAGE',
        ),
    ]
