# Generated by Django 5.2.8 on 2026-03-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_user'),
        ('users', '0002_factoryuser_wherehouses_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryuser',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
    ]
