# Generated by Django 5.2.8 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_factoryuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryuser',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token', max_length=255, null=True),
        ),
    ]
