# Generated by Django 5.2.8 on 2026-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_factoryuser_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryuser',
            name='fcm_token',
        ),
    ]
