# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_excuator_orders_page_factoryuser_excavators_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factoryuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='factoryuser',
            unique_together={('phone_number',)},
        ),
    ]
