# Generated by Django 5.2.8 on 2026-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
