# Generated by Django 5.2.8 on 2026-02-26 10:11

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(max_length=255)),
                ('crud_whouse', models.BooleanField(default=False)),
                ('crud_whouse_manager', models.BooleanField(default=False)),
                ('crud_factory_operator', models.BooleanField(default=False)),
                ('crud_driver', models.BooleanField(default=False)),
                ('crud_guard', models.BooleanField(default=False)),
                ('read_whouse', models.BooleanField(default=False)),
                ('read_whouse_manager', models.BooleanField(default=False)),
                ('read_factory_operator', models.BooleanField(default=False)),
                ('read_driver', models.BooleanField(default=False)),
                ('read_guard', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
