# Generated by Django 5.2.8 on 2026-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='crud_product_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='read_product_type',
            field=models.BooleanField(default=False),
        ),
    ]
