# Generated by Django 5.2.8 on 2026-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_userpermissions_crud_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='crud_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='read_transport',
            field=models.BooleanField(default=False),
        ),
    ]
