# Generated by Django 5.2.8 on 2026-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_userpermissions_crud_transport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissions',
            old_name='crud_product_type',
            new_name='crud_client',
        ),
        migrations.RenameField(
            model_name='userpermissions',
            old_name='read_product_type',
            new_name='crud_product',
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='read_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='read_product',
            field=models.BooleanField(default=False),
        ),
    ]
