# Generated by Django 5.2.8 on 2026-03-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_crud_product_type_userpermissions_crud_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='crud_whouse',
        ),
    ]
