# Generated by Django 5.2.8 on 2026-03-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='place',
        ),
    ]
