# Generated by Django 5.2.8 on 2026-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_alter_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='car_type',
            field=models.CharField(choices=[('EXCAVATOR', 'Excavator'), ('TRUCK', 'Truck')], default='TRUCK', max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=100),
        ),
    ]
