# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0002_alter_whouse_name'),
        ('transports', '0004_remove_duplicate_transports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='transport',
            unique_together={('number', 'whouse')},
        ),
    ]
