# Generated by Django 5.2.8 on 2026-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='CLIENTS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='DRIVERS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='MAIN_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='ORDERS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='PRODUCTS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='READY_PRODUCTS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='TRANSPORTS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='USERS_PAGE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='WHEREHOUSES_PAGE',
            field=models.BooleanField(default=False),
        ),
    ]
