# Generated by Django 5.2.8 on 2026-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0003_driver_photo'),
        ('files', '0002_alter_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car_type',
        ),
        migrations.AddField(
            model_name='driver',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='files.file'),
        ),
    ]
