# Generated by Django 5.2.8 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0004_remove_driver_car_number_remove_driver_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token', max_length=255, null=True),
        ),
    ]
