# Generated by Django 5.2.8 on 2026-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0005_driver_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='fcm_token',
        ),
    ]
