# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0007_alter_driver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='files',
        ),
    ]
