# Generated by Django 5.2.8 on 2026-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0008_remove_driver_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='SUPPLIERS_PAGE',
            field=models.BooleanField(default=False),
        ),
    ]
