# Generated by Django 5.2.8 on 2026-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0009_driver_suppliers_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='EXCUATOR_ORDERS_PAGE',
            field=models.BooleanField(default=False),
        ),
    ]
