# Generated by Django 5.2.8 on 2026-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0011_rename_excuator_orders_page_driver_excavators_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
