# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0012_driver_type_alter_driver_password'),
        ('factory_whouse', '0002_alter_whouse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('phone_number', 'whouse')},
        ),
    ]
