# Generated by Django 5.2.8 on 2026-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0013_alter_driver_options_alter_driver_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='CLIENTS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='DRIVERS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='EXCAVATORS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='MAIN_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ORDERS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='PRODUCTS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='READY_PRODUCTS_PAGE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='TRANSPORTS_PAGE',
            field=models.BooleanField(default=True),
        ),
    ]
