# Generated by Django 5.2.8 on 2026-03-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0002_driver_clients_page_driver_drivers_page_and_more'),
        ('filedatas', '0002_alter_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filedatas.file'),
        ),
    ]
