# Generated by Django 5.2.8 on 2026-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0002_alter_driver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
