# Generated by Django 5.2.8 on 2026-02-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0003_alter_driver_password'),
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='whouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse'),
        ),
    ]
