# Generated by Django 5.2.8 on 2026-03-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0006_remove_driver_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
