# Generated by Django 5.2.8 on 2026-03-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_drivers', '0010_driver_excuator_orders_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='EXCUATOR_ORDERS_PAGE',
            new_name='EXCAVATORS_PAGE',
        ),
    ]
