# Generated by Django 5.2.8 on 2026-02-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('whouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_operators', to='factory_whouse.whouse')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOperatorResetPasswordSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25)),
                ('otp', models.IntegerField(default=123456)),
                ('last_sms_time', models.DateTimeField(auto_now_add=True)),
                ('uses', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('factory_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_operator.factoryoperator')),
            ],
        ),
    ]
