# Generated by Django 5.2.8 on 2026-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryoperator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='factoryoperator',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoryoperator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
