# Generated by Django 5.2.8 on 2026-03-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
