# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORT', 'Transport'), ('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('SUBORDER', 'Suborder'), ('PRODUCT', 'Product'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
