# Generated by Django 5.2.8 on 2026-03-11 11:45

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_object_id_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORT', 'Transport'), ('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('SUBORDER', 'Suborder'), ('PRODUCT', 'Product'), ('OTHER', 'Other')], default='OTHER', max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
