# Generated by Django 5.2.8 on 2026-03-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_file_object_id_remove_file_type_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORT', 'Transport'), ('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('SUBORDER', 'Suborder'), ('PRODUCT', 'Product'), ('OTHER', 'Other'), ('EXCAVATOR_ORDER', 'Excavator Order'), ('EXCAVATOR_ORDER_BEFORE', 'Excavator Order Before'), ('EXCAVATOR_ORDER_AFTER', 'Excavator Order After'), ('EXCAVATOR_SUBORDER_BEFORE', 'Excavator Sub-Order Before'), ('EXCAVATOR_SUBORDER_AFTER', 'Excavator Sub-Order After')], default='OTHER', max_length=255),
        ),
    ]
