# Generated by Django 5.2.8 on 2026-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_documents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORT', 'Transport'), ('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('SUBORDER', 'Suborder'), ('PRODUCT', 'Product'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
