# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_documents_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('file', 'type', 'object_id')},
        ),
    ]
