# Generated by Django 5.2.8 on 2026-03-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0002_excavatororder_after_files_and_more'),
        ('factory_drivers', '0009_driver_suppliers_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatororder',
            name='after_files',
        ),
        migrations.RemoveField(
            model_name='excavatororder',
            name='after_sign',
        ),
        migrations.RemoveField(
            model_name='excavatororder',
            name='before_files',
        ),
        migrations.RemoveField(
            model_name='excavatororder',
            name='before_sign',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='is_external',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='excavatorsuborder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excavator_sub_orders', to='factory_drivers.driver'),
        ),
    ]
