# Generated by Django 5.2.8 on 2026-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0003_remove_excavatororder_after_files_and_more'),
        ('files', '0007_alter_documents_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='excavatorsuborder',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='excavator_suborder_files', to='files.file'),
        ),
    ]
