# Generated by Django 5.2.8 on 2026-03-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0004_remove_excavatorsuborder_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatororder',
            name='transport_type',
        ),
    ]
