# Generated by Django 5.2.8 on 2026-03-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0005_remove_excavatororder_transport_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavatororder',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='excavatororder',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='excavatororder',
            name='status_history',
        ),
        migrations.RemoveField(
            model_name='excavatororder',
            name='transport',
        ),
    ]
