# Generated by Django 5.2.8 on 2026-03-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0006_rename_latitude_excavatororder_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='files',
        ),
    ]
