# Generated by Django 5.2.8 on 2026-03-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0007_remove_excavatorsuborder_files'),
        ('factory_whouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatororder',
            name='whouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excavator_orders', to='factory_whouse.whouse'),
        ),
    ]
