# Generated by Django 5.2.8 on 2026-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0008_excavatororder_whouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatororder',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
