# Generated by Django 5.2.8 on 2026-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0009_excavatororder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatororder',
            name='external_drivers',
            field=models.JSONField(default=list),
        ),
    ]
