# Generated by Django 5.2.8 on 2026-03-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0010_excavatororder_external_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='excavatorsuborder',
            name='start_date',
        ),
    ]
