# Generated by Django 5.2.8 on 2026-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0011_remove_excavatorsuborder_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavatororder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
