# Generated by Django 5.2.8 on 2026-03-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0012_alter_excavatororder_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatororder',
            name='external_drivers',
        ),
    ]
