# Generated by Django 5.2.8 on 2026-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0013_remove_excavatororder_external_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavatororder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='excavatorsuborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
