# Generated by Django 5.2.8 on 2026-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0014_alter_excavatororder_status_and_more'),
        ('files', '0007_alter_documents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavatororder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='excavator_order_files', to='files.file'),
        ),
        migrations.AlterField(
            model_name='excavatorsuborder',
            name='after_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='excavator_suborder_after_files', to='files.file'),
        ),
        migrations.AlterField(
            model_name='excavatorsuborder',
            name='before_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='excavator_suborder_before_files', to='files.file'),
        ),
    ]
