# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0016_remove_duplicate_suborders'),
        ('factory_drivers', '0012_driver_type_alter_driver_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excavatororder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='excavatorsuborder',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='excavatororder',
            unique_together={('phone_number', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='excavatorsuborder',
            unique_together={('parent', 'driver')},
        ),
    ]
