# Generated by Django 5.2.8 on 2026-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0017_alter_excavatororder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatororder',
            name='rejector_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excavatororder',
            name='rejector_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='excavatororder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ON_WAY', 'On Way'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='excavatorsuborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ON_WAY', 'On Way'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
