# Generated by Django 5.2.8 on 2026-03-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0019_alter_excavatororder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excavatorsuborder',
            options={'ordering': ['-created_at']},
        ),
    ]
