# Generated by Django 5.2.8 on 2026-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0020_alter_excavatorsuborder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavatororder',
            name='rejector_id',
        ),
        migrations.AddField(
            model_name='excavatororder',
            name='rejector_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
