# Generated by Django 5.2.8 on 2026-04-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0021_alter_excavatororder_rejector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavatororder',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavatororder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
