# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='files',
        ),
    ]
