# Generated by Django 5.2.8 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0002_alter_whouse_name'),
        ('supplier', '0004_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplierphone',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('inn_number', 'whouse')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierphone',
            unique_together={('supplier', 'phone_number')},
        ),
    ]
