# Generated by Django 5.2.8 on 2026-03-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_options_alter_supplierphone_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('inn_number', 'type')},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='whouse',
        ),
    ]
