# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_phone_number_client_files_clientphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='files',
        ),
    ]
