# Generated by Django 5.2.8 on 2026-03-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientbranches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientphone',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='clientbranches',
            unique_together={('client', 'longitude', 'latitude')},
        ),
        migrations.AlterUniqueTogether(
            name='clientphone',
            unique_together={('client', 'phone_number')},
        ),
    ]
