# Generated by Django 5.2.8 on 2026-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_account_number_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='inn',
        ),
    ]
