# Generated by Django 5.2.8 on 2026-04-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbranches',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
