# Generated by Django 5.2.8 on 2026-03-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whouseproductshistory',
            name='files',
        ),
        migrations.RemoveField(
            model_name='whouseproductshistory',
            name='whouse_product',
        ),
        migrations.AlterField(
            model_name='whouseproductshistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='whouseproductshistory',
            name='status',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=20),
        ),
    ]
