# Generated by Django 5.2.8 on 2026-02-27 06:48

import apps.common.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
        ('products', '0002_alter_producttype_types_alter_producttype_unities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='unities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='whouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unity', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
                ('whouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
