# Generated by Django 5.2.8 on 2026-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_whouseproductshistory_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
    ]
