# Generated by Django 5.2.8 on 2026-03-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productitem_name'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproducts',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
