# Generated by Django 5.2.8 on 2026-02-28 10:07

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_whouse', '0001_initial'),
        ('filedatas', '0001_initial'),
        ('products', '0004_remove_product_type_remove_product_unity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhouseProducts',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='whouse_products', to='filedatas.file')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('whouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_whouse.whouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
