# Generated by Django 5.2.8 on 2026-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_whouseproducts_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whouseproducts',
            name='files',
        ),
    ]
