# Generated by Django 5.2.8 on 2026-02-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatas', '0001_initial'),
        ('products', '0005_whouseproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whouseproducts',
            name='files',
            field=models.ManyToManyField(related_name='whouse_products', to='filedatas.file'),
        ),
    ]
