# Generated by Django 5.2.8 on 2026-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_documents_type'),
        ('products', '0005_remove_whouseproducts_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproducts',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='whouse_product_files', to='files.file'),
        ),
    ]
