# Generated by Django 5.2.8 on 2026-03-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_whouseproducts_files'),
        ('users', '0006_factoryuser_suppliers_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproducts',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.factoryuser'),
        ),
    ]
