# Generated by Django 5.2.8 on 2026-03-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_whouseproducts_creator'),
        ('supplier', '0002_remove_supplier_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproductshistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
