# Generated by Django 5.2.8 on 2026-03-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_whouseproductshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproducts',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttype'),
        ),
    ]
