# Generated by Django 5.2.8 on 2026-03-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_whouseproductshistory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='products.product'),
        ),
        migrations.AddField(
            model_name='whouseproductshistory',
            name='wproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.whouseproducts'),
        ),
    ]
