# Generated by Django 5.2.8 on 2026-03-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productitem_raw_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='products.whouseproducts'),
        ),
    ]
