# Generated by Django 5.2.8 on 2026-03-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_options_alter_suborder_options_and_more'),
        ('products', '0010_alter_productitem_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproductshistory',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.suborderitem'),
        ),
    ]
