# Generated by Django 5.2.8 on 2026-03-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_whouseproductshistory_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='quantity_per_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='products.whouseproducts'),
        ),
    ]
