# Generated by Django 5.2.8 on 2026-03-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productitem_quantity_per_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whouseproductshistory',
            name='wproduct',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='products.product'),
        ),
    ]
