# Generated by Django 5.2.8 on 2026-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_whouseproductshistory_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='whouseproductshistory',
            name='obj_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
