# Generated by Django 5.2.8 on 2026-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_whouseproductshistory_obj_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.producttype'),
        ),
    ]
